### PR TITLE
Change clr_flag to not mute adpcm channels.

### PR DESCRIPTION
**Pull request by greyrogue**
This change assumes that this line from neogeodev is incorrect:
"Flags must be manually cleared, playing a new sample on the channel won't clear it and the channel will stay silent."
In the third party source ymfm_opn used in MAME, the last phrase ("and the channel will stay silent") is not implemented.  This change attempts to match the behavior of ymfm_opn.

### CODE REVIEW

**Comment by greyrogue** [comment]
This change appears to fix stereo in the Neo Geo core for Xeno Crisis.

**Comment by jotego** [comment]
Why do you register flag_mask instead of just using ~flag_ctl instead? I think it will be cleared not to produce a new signal. It would also be cleaner not to make operations on port assignments (ie only connect signals).

Did you try this with several games? It's common to fix one thing here and break another there, as you know.

**Comment by greyrogue** [comment]
The separate values for flag_mask and flag_ctl are too match the behavior of ymfm_opn, which goes flag_mask can always be read high once it's triggered until it's cleared by the Z80, unlike the flag_ctl, which is only a trigger. At least, that's how I understand the code in ymfm_opn.

It might be possible to write a simple program to test if ADPCMB samples are played if the flag isn't cleared first to verify this behavior.

I've tried this change with all the games I've had issues with before, and none of them seem to have regressions.

**Comment by jotego** [comment]
Thank you

**Pull request merged**
