### PR TITLE
Only update keyon events at the first operator

### PR DESCRIPTION
**Pull request by greyrogue**
--Fixes hi hat issue with Streets of Rage.

### CODE REVIEW

**Comment by greyrogue** [comment]
In addition to your comments about entry points, this will break non-6 channel versions, so that needs to be addressed as well.

**Comment by greyrogue** [comment]
Maybe there are four entry points, but they are only allowed to activate if the first operator will be the first one of the four to come out the drop of the last shift register (gated on correct value of next_op?).

**Comment by jotego** [comment]
Yes, I think that is what Nuke's code shows. So it is like the original file with your delay for the write; or your file with the original 2 (or 4) CSR instances.

**Comment by jotego** [comment]
Beautiful change. Thanks!

**Pull request merged**
