### PR TITLE
Fix the timers, Reset the registers.

### PR DESCRIPTION
**Pull request by sorgelig**
Basically the queue writes 0 to all ch/op while rst_n is active.
Some additional modifications added to let queue and clk_en be active while reset.

### CODE REVIEW

**Comment by jotego** [comment]
I don't know why you deleted if(rst) statements. Without those, simulations fail because registers start as X. I will put them back.
Thanks a lot for the other changes!

**Comment by sorgelig** [comment]
It's done on purpose because cen_cnt should count even in reset phase.

change the line to this:
reg [2:0] cen_cnt = 0;

it should fix the simulation.

**Comment by sorgelig** [comment]
You also can declare other signals with =0; so they all will have default state and rst will not required.
Otherwise reset for registers won't work. 
You revert of if(rst) makes line
```
.data ( rst ? {regop_width{1'b0}} : regop_in ),
```
useless as clk_en won't happen while rst=1.

**Comment by sorgelig** [comment]
by the way,
```
	.data	( rst ? {regop_width{1'b1}} : regop_in ),
```
1'b1 looks like not correct. Games have strange sound with such reset values. It should be 1'b0.

**Comment by sorgelig** [comment]
Also, since change to clock_enable version JT12 has something uninitialized at start. This makes PCM muted till something eventually get initialized later.
That's why i don't hear SEEEEGAAAA sound in Sonic if it's loaded together with core. And that's why Titan Overdrive 2 has no music.

**Comment by jotego** [comment]
It's funny because there is a report about needing 1's as initial values for JT51 (YM2151). I also know that RL registers need a 1 on startup and not a 0. I originally had some bits as 1 and some as 0on jt12_opram.v. I think that is what we need. It doesn't look as all flip flops were reset to the same value in real hardware.

**Comment by jotego** [comment]
@sorgelig , I have changed so as to have cen_cnt counting correctly during reset.
However, I have kept these lines of jt12_reg.v which you had deleted. Is there any problem with them?

	if( rst ) begin
		cnt		<= 5'h0;
		last	<= 1'b0;
		zero	<= 1'b1;
		busy_op	<= 1'b0;
		up_keyon_long <= 1'b0;
		cur_op  <= 2'd0;
		cur_ch  <= 3'd0;
	end

**Comment by sorgelig** [comment]
the address for opram consists on cur_op, cur_ch. If you keep them 0 while reset, then only settings for ch=0 op=0 will be cleared.

As for 0/1 - need more tests. Sonic had weird sound when i've used 1 for reset values.

**Comment by sorgelig** [comment]
I don't know what you mean by "reset all in one clock cycle". BRAM cannot be cleared in one clock cycle.
But if you've got an idea, then it's up to u how to implement it.

Reset is definitely much longer than 6 clock cycles. Reset is active while ROM is loading - so it's very long.

**Comment by jotego** [comment]
All register information was stored in flip flops on actual hardware and flip flops were connected in a shift register way as you can see in u_reg_ch of jt12_reg. Originally I had all made that way; but that takes a lot of room in the FPGA so I experimented with using a RAM, and that why some of them are in the jt12_opram module.

RAMs cannot be initialized in a clock cycle, but flip flops can. What I meant was to replace the RAM with individual flip flops for the OPerator bits, as it is the case now for the channel bits.

**Comment by sorgelig** [comment]
Sure, replacing to FF will allow to reset at single clock. I just remember you've told you wanted to keep LE as low as possible, that's why i've offered that reset. If saving of LE is not required, then other reset can be made.

**Comment by jotego** [comment]
The problem with a RAM like the one I am using now is that it is very wide (40 something bits) but it is not deep. So the implementation will basically waste many BRAM cells to create it or will actually create it off LE's (so no saving). To have a proper RAM implementation, I would need a faster clock so the whole depth of a BRAM can be used. The faster clock would allow to get many words out on a single FM clock cycle.
With the new clock-enable architecture, it is possible to operate a RAM at full clock speed and get 6 words out per FM clock cycle (as FM clock is 1/6 of main clock). If BRAM width is 9 bits (such as MiST or ZX-UNO), then I can get 54 bits per clock cycle. Maybe that is enough. I have to check...

**Comment by sorgelig** [comment]
what is more disturbing is that clock_enable version has something uninitialized, so Titan Overdrive 2 doesn't have music if loaded first. And Sonic has no SEEGAAA shouting at first start. Only when Sonic start to play the music, i can load Titan demo and it will have music.
This is most annoying and i cannot find where is the bug...

**Comment by jotego** [comment]
On first load, _Titan Overdirve 2_ and _Sonic_ have issues. Do you still get the problem after reset (without re-load)?

**Comment by sorgelig** [comment]
Reset doesn't fix the problem. If i reset Sonic before it start to play first music, then SEEGAA won't be played. I have to wait the first music to start playing then i can make reset and SEEGAA will be played.

**Comment by jotego** [comment]
Do you have "RL" bits set to 1? I have them like that in the latest commit. This was a known bug:

```
// RL is on a different register to 
// have the reset to 1
jt12_sh_rst #(.width(2),.stages(6),.rstval(1'b1)) u_regch_rl(
	.clk	( clk		),
	.clk_en	( clk_en	),
	.rst	( rst		),
	.din	( up_pms_ch	? rl_in :  rl	),
	.drop	( rl	)
);
```

**Comment by sorgelig** [comment]
i didn't set anything. 
If you show me what to patch, then i will try

**Comment by jotego** [comment]
It is checked in already. Pull the latest version.

**Comment by sorgelig** [comment]
nope. it doesn't fix the problem.
Also reset all regs to 1 making Sonic play weird. 
Probably some regs initialized to 1 and cannot be changed through normal register programming, or something like this.

**Comment by sorgelig** [comment]
i've just tried non-ce version with timer fixes applied. Sonic's SEEGAA plays at start. Titan doesn't play. So i have to start the Sonic and wait till music start to play. Then load Titan demo which plays fine afterward.

**Pull request merged**
