### PR TITLE
Export jt49 output enables (used by Alpha Densi 68k), fix .qip file, fix ADPCM-A enablers for YM2610 (NeoGeo)

### PR DESCRIPTION
**Pull request by gyurco**
Depends on https://github.com/jotego/jt49/pull/7

### CODE REVIEW

**Comment by jotego** [comment]
Is the _cen_ patch coming from the MiSTer version? 

About the negedge usage, when a signal gates the clock it should be latched at falling edge. The problem here is that Quartus seems to decide whether to use the _cen_ signals as clock enable inputs in the LUT or as clock gating signals in a rather whimsical way. I read recently that it's better to generate the clock gating signal and then effectively add a `clk & cen` assignment to force it. I want to check whether that reduces LUT usage or not, but I haven't had the time to do it.

I'm ok with merging this but we need to solve the question about the removed jt49 mux. It changes the functionality of a pin and I'm afraid it may break something in other cores.

**Comment by gyurco** [comment]
It's basically reverting the pre_xxx version (where there are no pre_cen_xxx and cen_xxx versions).
Do you think is it used as clock gating? My best knowledge is that clock gating on FPGAs are no-no, as it would affect the clock skew, and even if it's used, it requires special hardware elements, not just a simple gate. So clock enables are the common and recommended way.

I replied about the JT49 change, basically I can add a parameter to enable/disable the feedback logic.

**Comment by jotego** [comment]
I think most FPGAs have several clock gating structures, particularly at the root of each clock tree. That includes the Cyclone V series and I suppose Cyclone III. It's obvious that if you apply the signal once at the clock tree it will save resources. I just wasn't able to get consistent results a few years ago when I was trying it. I must try again, though, with the `clk & cen` syntax.

**Comment by gyurco** [comment]
As the number of clock networks are quite limited, and are described in the fitter output, I never seen any new global clock created from a clock-enable HDL construct. But I might be wrong here...

The most important part that ADPCM is broken with the current code in NeoGeo. Probably you can try it and hear it yourself (check Metal Slug intro for example, Gatling gun and "Metal Slug" announcement are both missing with the current jt12_div)

**Comment by gyurco** [comment]
But now you can try it on MiST, too :)
With the current jt12 (broken) or with this reverted (OK):
https://github.com/jotego/jt12/commit/d4607e1ec4857c7aab4660162e2da53d02fa3890
(or just with the simple patch above)

Here's the link:
https://github.com/gyurco/NeoGeo_MiSTer/tree/mist/mist

The theory about the clock gating might be OK, but as I said, I never seen any new global clock created from constructs like this. Only when a generated signal is used as clock, but that's a very different story, and should be avoided.

**Pull request merged**
