### PR TITLE
Registers part fix for jt10

### PR DESCRIPTION
**Pull request by furrtek**
Some registers didn't have part checks for writes, this was messing up the timer A (part 0) and some ADPCM-B (part 1) register values.

Also, IRQ enables for timers were swapped in jt12_top.

### CODE REVIEW

**Comment by jotego** [comment]
**Thanks** a lot for the patch. I have not applied it directly because I think all the control registers should be affected by the !part condition. 
Please have a look at this [commit](https://github.com/jotego/jt12/commit/f5604f3ea479c8ff9fee2c4483c782609e98a27a) I made based on your patch.

**Comment by furrtek** [comment]
Confirming that it works just as well :)

**Comment by jotego** [comment]
Great! I still have to check I didn’t break anything on the Megadrive but I
think it should be ok.

Notice that I have left the separated output signals. If you don’t need
them you can leave them unconnected in the instance. If you call the name
but leave empty the assignment in the brackets you won’t get any warning.
Like this

Jt10 myjt10(
.unused(     ),
// other stuff
);

**Comment by jotego** [comment]
Could you leave the separated output pins in jt12_top intact? They are used in other instantiations. For instance, they are used in the ZX Spectrum core of MiSTer (for recreating a real-life add-on with two YM2203) for instance.

I think the rest of the corrections are fine. If you reverse jt12_top I can do the merge.

**Comment by furrtek** [comment]
Didn't meant to update the file here, sorry. I'm still confused about some things with git, I'll restore jt12_top to your version with the separated outputs.

**Comment by jotego** [comment]
We left this thread open. Closing it!

**Pull request closed without merging**
